# -*- coding: utf-8 -*-
"""Star Wars API (SWAPI)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A1lI-dAbeMwmDCONinux5ocgaQ-EUkcs

# use get to request data from star war API (people)
- import requests
- create loop for 5 url API reqests
- get only name height mass birth_year url(homeworld) column
- create Dataframe with data by pandas dataframe
"""

from requests import get
import pandas as pd

url = "https://swapi.dev/api/people/"
data = []

for i in range(5):
    index = i + 1
    new_url = url + str(index)
    res = get(new_url)
    json_data = res.json()
    prep_data = {
        "name" : json_data["name"],
        "height" : json_data["height"],
        "mass" : json_data["mass"],
        "birth_year" : json_data["birth_year"],
        "url" : json_data["homeworld"]
    }
    data.append(prep_data)

df = pd.DataFrame(data)
print(df)

"""# use get to request data from star war API (people)
- create loop for 10 url API reqests
- get only name and url column
- create homeword dataframe
"""

from requests import get
import pandas as pd

url = "https://swapi.dev/api/planets/"

data2 = []

for i in range(10):
    index = i + 1
    new_url = url + str(index)
    wres = get(new_url)
    wjson_data = wres.json()
    wprep = {
        "homeworld_name" : wjson_data["name"],
        "url" : wjson_data["url"]
    }
    data2.append(wprep)

df2  = pd.DataFrame(data2)
print(df2)

"""# Merge 2 dataframe togeter with url colum and drop url column"""

merge_df = pd.merge(df, df2 ,on = "url")
full_df = merge_df.drop(["url"], axis= 1)
full_df

"""# Write CSV file"""

full_df.to_csv("Starwar.csv")